### ISSUE TITLE
Suggestion for input length??

### ISSUE THREAD

**Issue by ShashwatAgrawal20** [Khizarshah01/contentSummarizer#4]
idk but the min and max values seems too low. 
@Khizarshah01 any thoughts?
pinging @MrCracker-OP for suggesiton.

https://github.com/Khizarshah01/contentSummarizer/blob/577b0b0223297df3959993bb020b85a145da96d2/src/components/Home.jsx#L138-L139

**Comment by Khizarshah01** [comment]
The backend already have fixed length. so there is no reason for changing it on frontend side.

https://github.com/MrCracker-OP/summarizeback/blob/main/app.py

**Comment by MrCracker-OP** [comment]
> The backend already have fixed length. so there is no reason for changing it on frontend side.
> 
> https://github.com/MrCracker-OP/summarizeback/blob/main/app.py#L53

It's the default length, so it doesn't represent the minimum or maximum, It's handled on the frontend side

**Comment by ShashwatAgrawal20** [comment]
> The backend already have fixed length. so there is no reason for changing it on frontend side.
> 
> https://github.com/MrCracker-OP/summarizeback/blob/main/app.py#L53

As MrCracker said, It serves as a safety measure, functioning as the default size. If a user doesn't specify a length, the system won't encounter an error; instead, it will default to a length of 15.

https://github.com/MrCracker-OP/summarizeback/blob/fd0881e15c259845d4d983f4f37309d1387a8010/app.py#L53

**Comment by Khizarshah01** [comment]
okay, i will fix it.

**Comment by ShashwatAgrawal20** [comment]
> okay, i will fix it.

Maybe 25 or 30 seems like a reasonable max value.

**Comment by Khizarshah01** [comment]
Done!
